### ISSUE TITLE
Lost Connection to Server Error 

### ISSUE THREAD

**Issue by beginnercoder2** [prokolyvakis/node-red-contrib-sparql#2]
I am able to install the Sparql node. I downloaded python and install required libraries.. However, whenever I deploy the flow I lose connection to server and Node-red crushes. The error is written like below in cmd window. Do you know how to solve the problem?  Thank you in advance. 
```
[info] Stopping flows
[info] Stopped flows
[info] Starting flows
[info] [sparql:ee27e348.9600e] Python function '' running on PID undefined
[info] Started flows
[red] Uncaught Exception:
Error: spawn python ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:421:16)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)
```

**Comment by prokolyvakis** [comment]
Hello,

Could you please provide me with some further information regarding the environment under which you are testing it? Are you using MacOS, Linux, Windows? We have tested it under Mac OS and Linux environments. Moreover, could you please say to me which node-red and python versions are you using? 

With a little bit search that I did, I saw that this error usually happens to Windows Users. You can find some further information here: https://github.com/nodejs/node-gyp/issues/277 . I suspect that it is a problem with your Python installation.

**Comment by beginnercoder2** [comment]
Hello,
Thank you for the information. I was able to solve the problem. I changed the Python version 2.7 and made node-gyp settings. I am using Windows 10, node v -11.6.0. I dont have any experience with Python and need to understand the usage of the node to see the result of the query in Node-red. I am working on it but If you have any tutorial about the node or an example simple flow, could you share?

**Comment by prokolyvakis** [comment]
Hello again,

An example is provided here: https://github.com/prokolyvakis/node-red-contrib-sparql#usage
All you have to do is to properly configure it as it is described and to properly add a Node-RED (a) Inject node and (b) a Debug node.
