### ISSUE TITLE
ValueError: No JSON object could be decoded

### ISSUE THREAD

**Issue by JohnJGram** [prokolyvakis/node-red-contrib-sparql#3]
Hi!
I have a Windows 10 running node v10.15.3 npm v6.4.1. 
I was able to download and install the Sparql node. At the beginning i had the same problem of the other issue (Lost Connection to Server Error) but i was able to solve it by installing python 2.7
The new problem is the fact that when  I inject the flow as output in the debug/cmd window:

````
23 May 00:17:32 - [error] [sparql:Sparql] Traceback (most recent call last):
  File "<string>", line 89, in <module>
  File "C:\Users\User\.windows-build-tools\python27\lib\json\__init__.py", line 339, in loads

23 May 00:17:32 - [error] [sparql:Sparql]     return _default_decoder.decode(s)
  File "C:\Users\User\.windows-build-tools\python27\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\User\.windows-build-tools\python27\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

23 May 00:17:32 - [error] [sparql:Sparql] Python Function process exited with code 1
23 May 00:17:32 - [info] [sparql:Sparql] Python function 'Sparql' running on PID 8924
````

I'm really new at this. I just need this node to be working to make query to a stardog database for a university project. But the problem is that i can't make this node work with every kind on endpoint.
If you have any idea on what could be the problem you would help me a lot

**Comment by prokolyvakis** [comment]
Hello,

I am not using Windows, so I had never had the opportunity to test the node's functionality under them. Since it would be difficult for me to reproduce the error, I advice you to use it under a dockerized environment.

If you feel that you can fix it, feel free to create a pull request!
